# Render deployment configuration
services:
  - type: web
    name: financial-news-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18